### ISSUE TITLE
RepresenterError: Cannot represent Version

### ISSUE THREAD

**Issue by gokhanettin** [conan-io/hooks#332]
https://github.com/conan-io/hooks/blob/819a71d40f5d55aaebd0ed744a5b1e136cecca39/hooks/conan-center.py#L693-L705

Here `safe_dump` raises an error when I try to create packages using `conan_package_tools.`.

```
[HOOK - conan-center.py] post_export(): ERROR: [CONANDATA.YML REDUCE (KB-H031)] Exception raised from hook: ('cannot represent an object', '1.1.0') (https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#KB-H031) 
Traceback (most recent call last):
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/conans/client/hook_manager.py", line 63, in execute
    method(output=output, **kwargs)
  File "/home/gokhanettin/.conan/hooks/conan-center.py", line 121, in wrapper
    ret = func(output, *args, **kwargs)
  File "/home/gokhanettin/.conan/hooks/conan-center.py", line 676, in post_export
    def test(out):
  File "/home/gokhanettin/.conan/hooks/conan-center.py", line 142, in tmp
    raise e
  File "/home/gokhanettin/.conan/hooks/conan-center.py", line 136, in tmp
    ret = func(out)
  File "/home/gokhanettin/.conan/hooks/conan-center.py", line 690, in test
    new_conandata_yml = yaml.safe_dump(info, default_flow_style=False)
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/yaml/__init__.py", line 306, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/yaml/representer.py", line 207, in represent_dict
    return self.represent_mapping('tag:yaml.org,2002:map', data)
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/yaml/representer.py", line 117, in represent_mapping
    node_key = self.represent_data(item_key)
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/gokhanettin/.pyenv/versions/conan/lib/python3.9/site-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', '1.1.0')
```

A simple quick fix would be

```
version = str(conanfile.version)
```

It seems it cannot represent Version class, but converting to `str` works file.

**Comment by uilianries** [comment]
@gokhanettin Thank you for reporting. Are you interested on providing a PR? It seems be really simple fix.

**Comment by gokhanettin** [comment]
OK. I will send a PR.

**Comment by uilianries** [comment]
Thank you!
